name: VARS

on: workflow_dispatch

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  is-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variable
        run: |
          echo "NW=$(curl -s https://nwjs.io/versions | jq -r '.latest')" >> $GITHUB_ENV
      - name: Show Var
        run: |
          echo ${{env.NW}}

  build-linux:
    needs: [ is-latest ]
    runs-on: ubuntu-latest
    steps:
      - name: Show Vars
        run: |
          echo ${{env.NW}}

  build-release:
    needs: [ build-linux ]
    runs-on: ubuntu-latest
    steps:
      - name: Show Vars
        run: |
          echo ${{env.NW}}

